version: '3.1'
services:

  word-counter:
    container_name: word_counter
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "SPRING_PROFILES_ACTIVE=default"
    ports:
      - "8080:8080"
      - "10005:8000"