server:
  port: 8081
  servlet:
    context-path: /word-counter

## Configuring actuator/info endpoint
info:
  app:
    name: word-counter
    description: Word Counter API
    version: 0.0.1


swagger:
  title: word-counter
  description: Word Counter API
  version: 0.0.1
  termsOfServiceUrl: \#
  contactName: Dzmitry Harlach
  contactUrl: \#
  contactEmail: harlachdzmitry@gmail.com
  license: License of API
  licenseUrl: \#
